//internal imports
import AuthProvider from "@/elements/AuthProvider";
import { ChildrenType } from "@/types/types";
//import styles
import "./globals.css";
import LightProvider from "@/elements/lightProvider";
import { DM_Sans, DM_Serif_Display } from "next/font/google";

//export site's metadata
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const dm_sams = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  variable: "--font-dm-sans",
});

const dm_serif_display = DM_Serif_Display({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-dm-serif",
});

export default function RootLayout({ children }: ChildrenType) {
  return (
    <html lang="en">
      <body className={`${dm_sams.variable} ${dm_serif_display.variable}`}>
        <LightProvider>
          <AuthProvider>{children}</AuthProvider>
        </LightProvider>
      </body>
    </html>
  );
}
